const currencyCodes = [
    { label: "Afghanistan", value: "AFN" },
    { label: "Albania", value: "ALL" },
    { label: "Algeria", value: "DZD" },
    { label: "Andorra", value: "EUR" },
    { label: "Angola", value: "AOA" },
    { label: "Antigua and Barbuda", value: "XCD" },
    { label: "Argentina", value: "ARS" },
    { label: "Armenia", value: "AMD" },
    { label: "Australia", value: "AUD" },
    { label: "Austria", value: "EUR" },
    { label: "Azerbaijan", value: "AZN" },
    { label: "Bahamas", value: "BSD" },
    { label: "Bahrain", value: "BHD" },
    { label: "Bangladesh", value: "BDT" },
    { label: "Barbados", value: "BBD" },
    { label: "Belarus", value: "BYN" },
    { label: "Belgium", value: "EUR" },
    { label: "Belize", value: "BZD" },
    { label: "Benin", value: "XOF" },
    { label: "Bhutan", value: "BTN" },
    { label: "Bolivia", value: "BOB" },
    { label: "Bosnia and Herzegovina", value: "BAM" },
    { label: "Botswana", value: "BWP" },
    { label: "Brazil", value: "BRL" },
    { label: "Brunei", value: "BND" },
    { label: "Bulgaria", value: "BGN" },
    { label: "Burkina Faso", value: "XOF" },
    { label: "Burundi", value: "BIF" },
    { label: "Cambodia", value: "KHR" },
    { label: "Cameroon", value: "XAF" },
    { label: "Canada", value: "CAD" },
    { label: "Cape Verde", value: "CVE" },
    { label: "Central African Republic", value: "XAF" },
    { label: "Chad", value: "XAF" },
    { label: "Chile", value: "CLP" },
    { label: "China", value: "CNY" },
    { label: "Colombia", value: "COP" },
    { label: "Comoros", value: "KMF" },
    { label: "Congo", value: "XAF" },
    { label: "Costa Rica", value: "CRC" },
    { label: "Croatia", value: "HRK" },
    { label: "Cuba", value: "CUP" },
    { label: "Cyprus", value: "EUR" },
    { label: "Czech Republic", value: "CZK" },
    { label: "Democratic Republic of the Congo", value: "CDF" },
    { label: "Denmark", value: "DKK" },
    { label: "Djibouti", value: "DJF" },
    { label: "Dominica", value: "XCD" },
    { label: "Dominican Republic", value: "DOP" },
    { label: "East Timor", value: "USD" },
    { label: "Ecuador", value: "USD" },
    { label: "Egypt", value: "EGP" },
    { label: "El Salvador", value: "USD" },
    { label: "Equatorial Guinea", value: "XAF" },
    { label: "Eritrea", value: "ERN" },
    { label: "Estonia", value: "EUR" },
    { label: "Ethiopia", value: "ETB" },
    { label: "Fiji", value: "FJD" },
    { label: "Finland", value: "EUR" },
    { label: "France", value: "EUR" },
    { label: "Gabon", value: "XAF" },
    { label: "Gambia", value: "GMD" },
    { label: "Georgia", value: "GEL" },
    { label: "Germany", value: "EUR" },
    { label: "Ghana", value: "GHS" },
    { label: "Greece", value: "EUR" },
    { label: "Grenada", value: "XCD" },
    { label: "Guatemala", value: "GTQ" },
    { label: "Guinea", value: "GNF" },
    { label: "Guinea-Bissau", value: "XOF" },
    { label: "Guyana", value: "GYD" },
    { label: "Haiti", value: "HTG" },
    { label: "Honduras", value: "HNL" },
    { label: "Hungary", value: "HUF" },
    { label: "Iceland", value: "ISK" },
    { label: "India", value: "INR" },
    { label: "Indonesia", value: "IDR" },
    { label: "Iran", value: "IRR" },
    { label: "Iraq", value: "IQD" },
    { label: "Ireland", value: "EUR" },
    { label: "Israel", value: "ILS" },
    { label: "Italy", value: "EUR" },
    { label: "Ivory Coast", value: "XOF" },
    { label: "Jamaica", value: "JMD" },
    { label: "Japan", value: "JPY" },
    { label: "Jordan", value: "JOD" },
    { label: "Kazakhstan", value: "KZT" },
    { label: "Kenya", value: "KES" },
    { label: "Kiribati", value: "AUD" },
    { label: "Kuwait", value: "KWD" },
    { label: "Kyrgyzstan", value: "KGS" },
    { label: "Laos", value: "LAK" },
    { label: "Latvia", value: "EUR" },
    { label: "Lebanon", value: "LBP" },
    { label: "Lesotho", value: "LSL" },
    { label: "Liberia", value: "LRD" },
    { label: "Libya", value: "LYD" },
    { label: "Liechtenstein", value: "CHF" },
    { label: "Lithuania", value: "EUR" },
    { label: "Luxembourg", value: "EUR" },
    { label: "Madagascar", value: "MGA" },
    { label: "Malawi", value: "MWK" },
    { label: "Malaysia", value: "MYR" },
    { label: "Maldives", value: "MVR" },
    { label: "Mali", value: "XOF" },
    { label: "Malta", value: "EUR" },
    { label: "Marshall Islands", value: "USD" },
    { label: "Mauritania", value: "MRU" },
    { label: "Mauritius", value: "MUR" },
    { label: "Mexico", value: "MXN" },
    { label: "Micronesia", value: "USD" },
    { label: "Moldova", value: "MDL" },
    { label: "Monaco", value: "EUR" },
    { label: "Mongolia", value: "MNT" },
    { label: "Montenegro", value: "EUR" },
    { label: "Morocco", value: "MAD" },
    { label: "Mozambique", value: "MZN" },
    { label: "Myanmar", value: "MMK" },
    { label: "Namibia", value: "NAD" },
    { label: "Nauru", value: "AUD" },
    { label: "Nepal", value: "NPR" },
    { label: "Netherlands", value: "EUR" },
    { label: "New Zealand", value: "NZD" },
    { label: "Nicaragua", value: "NIO" },
    { label: "Niger", value: "XOF" },
    { label: "Nigeria", value: "NGN" },
    { label: "North Korea", value: "KPW" },
    { label: "North Macedonia", value: "MKD" },
    { label: "Norway", value: "NOK" },
    { label: "Oman", value: "OMR" },
    { label: "Pakistan", value: "PKR" },
    { label: "Palau", value: "USD" },
    { label: "Palestine", value: "ILS" },
    { label: "Panama", value: "PAB" },
    { label: "Papua New Guinea", value: "PGK" },
    { label: "Paraguay", value: "PYG" },
    { label: "Peru", value: "PEN" },
    { label: "Philippines", value: "PHP" },
    { label: "Poland", value: "PLN" },
    { label: "Portugal", value: "EUR" },
    { label: "Qatar", value: "QAR" },
    { label: "Romania", value: "RON" },
    { label: "Russia", value: "RUB" },
    { label: "Rwanda", value: "RWF" },
    { label: "Saint Kitts and Nevis", value: "XCD" },
    { label: "Saint Lucia", value: "XCD" },
    { label: "Saint Vincent and the Grenadines", value: "XCD" },
    { label: "Samoa", value: "WST" },
    { label: "San Marino", value: "EUR" },
    { label: "Sao Tome and Principe", value: "STN" },
    { label: "Saudi Arabia", value: "SAR" },
    { label: "Senegal", value: "XOF" },
    { label: "Serbia", value: "RSD" },
    { label: "Seychelles", value: "SCR" },
    { label: "Sierra Leone", value: "SLL" },
    { label: "Singapore", value: "SGD" },
    { label: "Slovakia", value: "EUR" },
    { label: "Slovenia", value: "EUR" },
    { label: "Solomon Islands", value: "SBD" },
    { label: "Somalia", value: "SOS" },
    { label: "South Africa", value: "ZAR" },
    { label: "South Korea", value: "KRW" },
    { label: "South Sudan", value: "SSP" },
    { label: "Spain", value: "EUR" },
    { label: "Sri Lanka", value: "LKR" },
    { label: "Sudan", value: "SDG" },
    { label: "Suriname", value: "SRD" },
    { label: "Sweden", value: "SEK" },
    { label: "Switzerland", value: "CHF" },
    { label: "Syria", value: "SYP" },
    { label: "Taiwan", value: "TWD" },
    { label: "Tajikistan", value: "TJS" },
    { label: "Tanzania", value: "TZS" },
    { label: "Thailand", value: "THB" },
    { label: "Togo", value: "XOF" },
    { label: "Tonga", value: "TOP" },
    { label: "Trinidad and Tobago", value: "TTD" },
    { label: "Tunisia", value: "TND" },
    { label: "Turkey", value: "TRY" },
    { label: "Turkmenistan", value: "TMT" },
    { label: "Tuvalu", value: "AUD" },
    { label: "Uganda", value: "UGX" },
    { label: "Ukraine", value: "UAH" },
    { label: "United Arab Emirates", value: "AED" },
    { label: "United Kingdom", value: "GBP" },
    { label: "United States", value: "USD" },
    { label: "Uruguay", value: "UYU" },
    { label: "Uzbekistan", value: "UZS" },
    { label: "Vanuatu", value: "VUV" },
    { label: "Vatican City", value: "EUR" },
    { label: "Venezuela", value: "VES" },
    { label: "Vietnam", value: "VND" },
    { label: "Yemen", value: "YER" },
    { label: "Zambia", value: "ZMW" },
    { label: "Zimbabwe", value: "ZWL" },
  ];
  
  export default currencyCodes;
  